apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: podinfo-example
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: podinfo
      repository: https://stefanprodan.github.io/podinfo
      version: 6.4.0 ## To use devlopment versions, set ">0.0.0-0"
    namespace: podinfo
    values:
      service:
        type: ClusterIP
    set:
      - name: service.enabled
        value: "True"
  providerConfigRef:
    name: helm-provider