        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        metadata:
          name: newcluster
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: default
              name: xplane-eks-cluster
              key: kubeconfig
