apiVersion: v1
kind: Secret
metadata:
  name: postgres-root-user-password
  namespace: default
data:
  password: bXlzZWNyZXRQYXNzd29yZDEh # mysecretPassword1!
---
apiVersion: springexample.io/v1alpha1
kind: RelationalDatabase
metadata:
  name: test-aurora-postgresql-db
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      springexample.io/provider: aws
      springexample.io/environment: staging
      springexample.io/createDBSubnetGroup: "true"
  writeConnectionSecretToRef:
    name: test-aurora-postgresql-db # secret contains endpoint, username, and password.
  resourceConfig:
    providerConfigName: default
    region: ap-northeast-1
    tags:
      - key: testKey
        value: testValue
  databaseName: "test"
  subnetIds:
    - subnet-0337116de2b474ce0
    - subnet-0283ff583579d3c42
  vpcId: vpc-0b1381fe9e0bfec54