apiVersion: springexample.io/v1alpha1
kind: RelationalDatabase
metadata:
  name: test-postgresql-db
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      springexample.io/provider: aws
      springexample.io/environment: dev
      springexample.io/createDBSubnetGroup: "true"
  writeConnectionSecretToRef:
    name: test-postgresql-db # secret contains endpoint, username, and password.
  resourceConfig:
    providerConfigName: default
    region: ap-northeast-1
    tags:
      - key: env
        value: test
  storageGB: 100
  subnetIds:
    - subnet-0337116de2b474ce0 # change these values before use
    - subnet-0283ff583579d3c42
  vpcId: vpc-0b1381fe9e0bfec54